[build]
  command = "npm run build:rss"
  publish = "dist-rss"
  functions = "netlify/functions"

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  force = true

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
